export const albums = [
    {
        id: 'goodbye-and-good-riddance',
        title: 'Goodbye & Good Riddance',
        artist: 'Juice WRLD',
        year: 2018,
        cover: './covers/goodbye-and-good-riddance.jpg',
        tracks: [
            "Intro",
            "All Girls Are The Same",
            "Lucid Dreams",
            "Lean Wit Me",
            "Wasted (feat. Lil Uzi Vert)",
            "I'm Still",
            "Betrayal - Skit",
            "Candles",
            "Scared Of Love",
            "Used To",
            "Karma - Skit",
            "Hurt Me",
            "Black & White",
            "Long Gone",
            "End Of The Road",
            "I'll Be Fine"
        ]
    },
    {
        id: 'wrld-on-drugs',
        title: 'Future & Juice WRLD Present... WRLD ON DRUGS',
        artist: 'Future & Juice WRLD',
        year: 2018,
        cover: './covers/wrld-on-drugs.jpg',
        tracks: [
            "Jet Lag (feat. Young Scooter)",
            "Astronauts",
            "Fine China",
            "Red Bentley (feat. Young Thug)",
            "Make It Back",
            "Oxy (feat. Lil Wayne)",
            "7 AM Freestyle",
            "Different (feat. Yung Bans)",
            "Shorty",
            "Realer N Realer",
            "No Issue",
            "WRLD On Drugs",
            "Afterlife",
            "Ain't Livin Right (feat. Gunna)",
            "Transformer (feat. Nicki Minaj)",
            "Hard Work Pays Off"
        ]
    },
    {
        id: 'death-race-for-love',
        title: 'Death Race for Love',
        artist: 'Juice WRLD',
        year: 2019,
        cover: './covers/death-race-for-love.jpg',
        tracks: [
            "Empty",
            "Maze",
            "HeMotions",
            "Demonz (feat. Brent Faiyaz) - Interlude",
            "Fast",
            "Hear Me Calling",
            "Big",
            "Robbery",
            "Flaws And Sins",
            "Feeling",
            "Syphilis",
            "Who Shot Cupid?",
            "Ring Ring (feat. Clever)",
            "Desire",
            "Out My Way",
            "The Bees Knees",
            "ON GOD (feat. Young Thug)",
            "10 Feet",
            "Won't Let Go",
            "She's The One",
            "Rider",
            "Make Believe"
        ]
    },
    {
        id: 'legends-never-die',
        title: 'Legends Never Die',
        artist: 'Juice WRLD',
        year: 2020,
        cover: './covers/legends-never-die.jpg',
        tracks: [
            "Anxiety - Intro",
            "Conversations",
            "Titanic",
            "Bad Energy",
            "Righteous",
            "Blood On My Jeans",
            "Smile (with The Weeknd)",
            "Tell Me U Luv Me (with Trippie Redd)",
            "Hate The Other Side",
            "Get Through It - Interlude",
            "Life's A Mess (feat. Halsey)",
            "Come & Go (with Marshmello)",
            "I Want It",
            "Fighting Demons",
            "Wishing Well",
            "Screw Juice",
            "Up Up And Away",
            "The Man, The Myth, The Legend - Interlude",
            "Stay High",
            "Can't Die",
            "Man Of The Year",
            "Juice WRLD Speaks From Heaven - Outro"
        ]
    },
    {
        id: 'fighting-demons',
        title: 'Fighting Demons',
        artist: 'Juice WRLD',
        year: 2021,
        cover: './covers/fighting-demons.jpg',
        tracks: [
            "Burn",
            "Already Dead",
            "You Wouldn't Understand",
            "Wandered To LA (with Justin Bieber)",
            "Eminem Speaks",
            "Rockstar In His Prime",
            "Doom",
            "Go Hard",
            "Juice WRLD Speaks",
            "Not Enough",
            "Feline (with Polo G & Trippie Redd)",
            "Relocate",
            "Juice WRLD Speaks 2",
            "Until The Plug Comes Back Around",
            "From My Window",
            "Girl Of My Dreams (with SUGA of BTS)",
            "Feel Alone",
            "My Life In A Nutshell"
        ]
    },
    {
        id: 'the-party-never-ends',
        title: 'The Party Never Ends',
        artist: 'Juice WRLD',
        year: 2024,
        cover: './covers/the-party-never-ends.jpg',
        tracks: [
            "The Party Never Ends",
            "Misfit",
            "AGATS2 (Insecure) [with Nicki Minaj]",
            "Lace It (with Eminem & benny blanco)",
            "Cuffed",
            "KTM Drip",
            "Love Letter",
            "Condone It",
            "Goodbye",
            "Party By Myself",
            "Adore You",
            "Celebrate (with Offset)",
            "Jeffrey",
            "Barbarian",
            "Best Friend (with Fall Out Boy)",
            "Floor It",
            "Oxycodone",
            "Spend It"
        ]
    }
];
